### ISSUE TITLE
Crash with error (.NET PenIMC.dll) at program start

### ISSUE THREAD

**Issue by token0** [bitbeans/SimpleDnsCrypt#147]
After WindowsUpdate installed some .NET updates, program won't start anymore. 
Throws an error(quoted in the end), then crashes.

Searching leads to new version of PenIMC.dll:
version 3.0.6920.8773
date of modification 16.05.2017 0:03

```
C:\Windows\Microsoft.NET\Framework\v3.0\WPF\PenIMC.dll
CRC32: 377FF18E
MD5: BC7AFE70E5269F5D78B7C777E8892517
SHA-1: F3D919687B8DAB5E70ED4615456FD6978C452D73
68 752 bytes
```

```
C:\Windows\Microsoft.NET\Framework64\v3.0\WPF
CRC32: 304A8C3E
MD5: 7DFAFBDB2168605745432DDBB69095B3
SHA-1: BA5F9908295637BD1A6F1A3B5D05EB41FCC732F5
85 648 bytes
```

This update was installed the same date and time (16.05.2017 0:05):
[KB4019112: Security and Quality Rollup for the .NET Framework 3.5.1, 4.5.2, 4.6, 4.6.1, and 4.6.2 updates for Windows 7 Service Pack 1 and Windows Server 2008 R2 Service Pack 1: May 9, 2017](https://support.microsoft.com/en-us/help/4019112/security-and-quality-rollup-for-the-net-framework-3-5-1-4-5-2-4-6-4-6)

------------------------

```
Message: The type initializer for 'MS.Win32.Penimc.UnsafeNativeMethods' threw an exception.
StackTrace:    at MS.Win32.Penimc.UnsafeNativeMethods.CreateResetEvent(IntPtr& handle)

   at System.Windows.Input.PenThreadWorker..ctor()

   at System.Windows.Input.PenThreadPool.GetPenThreadForPenContextHelper(PenContext penContext)

   at System.Windows.Input.PenThreadPool.GetPenThreadForPenContext(PenContext penContext)

   at System.Windows.Input.StylusWisp.WispTabletDeviceCollection.UpdateTabletsImpl()

   at System.Windows.Input.StylusWisp.WispTabletDeviceCollection.UpdateTablets()

   at System.Windows.Input.StylusWisp.WispTabletDeviceCollection..ctor()

   at System.Windows.Input.StylusWisp.WispLogic.get_WispTabletDevices()

   at System.Windows.Input.StylusWisp.WispLogic.RegisterHwndForInput(InputManager inputManager, PresentationSource inputSource)

   at System.Windows.Interop.HwndStylusInputProvider..ctor(HwndSource source)

   at System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)

   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)

   at System.Windows.Window.CreateSourceWindowDuringShow()

   at System.Windows.Window.SafeCreateWindowDuringShow()

   at System.Windows.Window.ShowHelper(Object booleanBox)

   at System.Windows.Window.Show()

   at SimpleDnsCrypt.AppWindowManager.ShowWindow(Object rootModel, Object context, IDictionary`2 settings)

   at Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType, IDictionary`2 settings)

   at SimpleDnsCrypt.SimpleDnsCryptBootstraper.OnStartup(Object sender, StartupEventArgs e)

   at System.Windows.Application.OnStartup(StartupEventArgs e)

   at System.Windows.Application.<.ctor>b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by token0** [comment]
Solution from M$: reinstall .NET 4.7
https://support.microsoft.com/en-us/help/4033488/comexception-error-from-wpf-applications-after-the-net-framework-4-7-i
