### ISSUE TITLE
Stops working randomly

### ISSUE THREAD

**Issue by vertigo220** [bitbeans/SimpleDnsCrypt#336]
Everyone once in a while, SDC will stop working and I'll lose all internet. I have to open the interface and stop then restart the service and then everything will be fine again. It's happened a couple times or so in the last few months (so pretty infrequently), then both yesterday and today. I'm running 0.5.6 on Win10x64. Based on the logs, it seems like maybe it's being caused when it tries to contact the update server, but I'm not sure. Please let me know if you need anything else.

[2018-07-21 03_24_05_Error.log](https://github.com/bitbeans/SimpleDnsCrypt/files/2217382/2018-07-21.03_24_05_Error.log)
[2018-07-22 16_37_11_Error.log](https://github.com/bitbeans/SimpleDnsCrypt/files/2217383/2018-07-22.16_37_11_Error.log)

**Comment by jedisct1** [comment]
```
2018-07-21 03:24:05.0653 ApplicationUpdater System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
```

**Comment by vertigo220** [comment]
Not sure what that reply is about, but I just had it happen again, though this time when I opened the SimpleDNSCrypt window the service had turned itself off. I like the idea of this program, but it is proving to be _extremely_ unreliable/unstable.

**Comment by tomw37066** [comment]
I had this issue and simply went to the properties for the DNSClient proxy service and set to "Restart the Service" after the first, second , and subsequent failures under the "Recovery" tab. No problems since .

**Comment by Jan02** [comment]
choose resolvers from your country

**Comment by glnzglnz** [comment]
Please see my maybe related thread at
[https://github.com/bitbeans/SimpleDnsCrypt/issues/356](https://github.com/bitbeans/SimpleDnsCrypt/issues/356)
