### ISSUE TITLE
automatic update not working

### ISSUE THREAD

**Issue by anonimi1** [bitbeans/SimpleDnsCrypt#351]
Windows 7 x64
I downloaded and installed the x64 version of DNS Crypt.
the program working normally until an automatic update happens on startup:

start the program normally. the following messages appears:
downloading signature...
downloading installer...
starting the update...

the program stuck on the splash screen with "starting the update message".

in the log i see
2018-09-19 16:47:02.1472 LoaderViewModel System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at SimpleDnsCrypt.ViewModels.LoaderViewModel.<InitializeApplication>d__8.MoveNext()

**Comment by bitbeans** [comment]
https://github.com/bitbeans/SimpleDnsCrypt#status 

The automatic update in version 0.5.6 is faulty. An update to 0.5.8 must be done manually.
