### ISSUE TITLE
Queries time out, have to restart DNSCrypt service

### ISSUE THREAD

**Issue by mr-brunes** [bitbeans/SimpleDnsCrypt#477]
I've noticed this happens fairly regularly.

PS C:\Windows\system32> nslookup www.bbc.co.uk
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  ::1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out

Query log shows requests timing out:

time:1580652681	host:::1	message:www.bbc.co.uk	type:AAAA	return:SYNTH	cached:0	duration:0	server:-
time:1580652682	host:::1	message:www.bbc.co.uk.localdomain	type:A	return:SERVER_TIMEOUT	cached:0	duration:5002	server:cisco
time:1580652684	host:::1	message:www.bbc.co.uk	type:A	return:SERVER_TIMEOUT	cached:0	duration:5000	server:cisco

Error log shows:
2020-02-02 14:10:29.9248 ApplicationUpdater System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<GetByteArrayAsyncCore>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SimpleDnsCrypt.Helper.ApplicationUpdater.<DownloadRemoteUpdateFileAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SimpleDnsCrypt.Helper.ApplicationUpdater.<CheckForRemoteUpdateAsync>d__1.MoveNext()

Toggling the DNSCrypt Service allows requests to work again.

**Comment by pc-v2** [comment]
i got this issue as well, working well with dns-proxy-2 cmd version
