### ISSUE TITLE
Can't open Resolvers menu at all

### ISSUE THREAD

**Issue by skeith** [bitbeans/SimpleDnsCrypt#483]
At first having this issue with my existing simplednscrypt install. Tried reinstall just in case and the problem persist.

Issues:

- dnscrypt service won't start/installed, after a while the app just close itself
- resolver menu won't open, clicking it will make the app freeze then close itself

Error log says these

```
2020-02-25 20:34:12.4134 ProcessHelper System.Exception: Timed out
   at SimpleDnsCrypt.Helper.ProcessHelper.ExecuteWithArguments(String filename, String arguments)
2020-02-25 20:34:22.8263 ProcessHelper System.Exception: Timed out
   at SimpleDnsCrypt.Helper.ProcessHelper.ExecuteWithArguments(String filename, String arguments)
```

**Comment by slyphnier** [comment]
did u try whitelist simplednscrypt in your antivirus/internet-security application ?
if you not sure how to whitelist it, u can try disable internet-security, and try run simplednscrypt, see if still throwing error or not 

make sure you enable your av/internet-security again afterwards

**Comment by skeith** [comment]
> did u try whitelist simplednscrypt in your antivirus/internet-security application ?
> if you not sure how to whitelist it, u can try disable internet-security, and try run simplednscrypt, see if still throwing error or not
> 
> make sure you enable your av/internet-security again afterwards

- I don't use any antivirus but the default windows defender which still on its default setting
- I have used simplednscrypt for almost a year with the same setup on the same pc (environment) without issue until it started doing this 5 days ago
- I switched to the original dnscrypt-proxy and it works flawlessly
