### ISSUE TITLE
crash and disappear after open

### ISSUE THREAD

**Issue by Mowzen** [bitbeans/SimpleDnsCrypt#532]
windows 10 x64
.net framework 4.8
microsoft visual c++ 2015-2019 x64 v14.28.29325
simple dnscrypt 0.7.1 x64 dnscrypt-proxy 2.0.42
in resolvers tab:
no resolvers have been loaded yet
in log folder:
2021-01-24 00:56:59.3402 ProcessHelper System.Exception: Timed out
   at SimpleDnsCrypt.Helper.ProcessHelper.ExecuteWithArguments(String filename, String arguments)
2021-01-24 00:57:08.4662 ProcessHelper System.Exception: Timed out
   at SimpleDnsCrypt.Helper.ProcessHelper.ExecuteWithArguments(String filename, String arguments)

----------------------
after 1 minutes app crash and close automatically

**Comment by itz0** [comment]
Same trouble with Win 10 LTSC, not open configuration window after install, i try both x64-x32 versions..
