### ISSUE TITLE
"This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread"

### ISSUE THREAD

**Issue by jedisct1** [bitbeans/SimpleDnsCrypt#85]
Just got this stack trace when trying to update the resolvers list (with the just released version 0.3.8)

![screen shot 2017-01-03 at 11 27 42 am](https://cloud.githubusercontent.com/assets/124872/21605196/cef10a42-d1a7-11e6-9daf-1ee45cf59c99.jpg)

**Comment by MacgyverJohnson** [comment]
Me too..
Updated over previous installation of 0.3.7....DNS cache service is enabled...Using Windows 8.1 Pro 64bit...
run at admin previledge....
Full message in text 
```
Message: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
StackTrace:    at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at SimpleDnsCrypt.ViewModels.MainViewModel.<RefreshResolverListAsync>d__104.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
